resolver: lts-17.2
packages: 
  - .
extra-deps:
  - hakyll-4.13.4.1
  - pandoc-2.10.1
  - pandoc-citeproc-0.17.0.2
  - pandoc-types-1.21
  - commonmark-0.1.1.2
  - commonmark-extensions-0.2.0.4
  - commonmark-pandoc-0.2.0.1
  - doctemplates-0.8.3
  - hslua-1.1.2
  - hslua-module-text-0.2.1
  - skylighting-0.8.5
  - skylighting-core-0.8.5
system-ghc: true
